name: "Program Overview"
version: "1.0"
component: "ProgramOverviewSection"
file: "client/src/components/career-programs/ProgramOverviewSection.tsx"
description: "Grid of cards highlighting key program characteristics"

when_to_use: |
  Use after the hero to quickly communicate what makes the program unique.
  Typically shows 3 cards with format, prerequisites, and difficulty level.

props:
  title:
    type: string
    required: true
    example: "Program Overview"
    
  subtitle:
    type: string
    required: false
    example: "Everything you need to become a professional developer"
    
  cards:
    type: array
    required: true
    description: "Array of overview cards (recommended: 3 cards)"
    items:
      icon:
        type: string
        description: "Tabler icon name"
        example: "DeviceLaptop"
      title:
        type: string
        example: "Self-Paced Learning"
      description:
        type: string
        example: "Learn on your own schedule with 24/7 access"
