name: "Numbered Steps"
version: "1.0"
component: "NumberedSteps"
file: "client/src/components/NumberedSteps.tsx"
description: "Displays a numbered list of steps with icons in a 3-column grid layout, with optional title, description and link"

when_to_use: |
  Use for showing sequential processes, how-to guides, or multi-step workflows.
  Great for refund processes, onboarding steps, career development phases, or any content 
  that benefits from numbered, visual step-by-step presentation.

props:
  title:
    type: string
    required: true
    description: "Main heading for the section (h2)"
    example: "How the Refund Works"
    
  description:
    type: string
    required: false
    description: "Optional paragraph text below the title, centered"
    example: "Our commitment to your success means a full refund if you meet the criteria."
    
  description_link:
    type: object
    required: false
    description: "Optional link displayed below the description"
    fields:
      text:
        type: string
        description: "Link text"
        example: "Conditions Apply."
      url:
        type: string
        description: "Link URL"
        example: "/terms-and-conditions"
        
  background:
    type: string
    required: false
    description: "Tailwind background class for the section"
    example: "bg-muted/30"
    default: "bg-muted/30"
    
  steps:
    type: array
    required: true
    description: "Array of step objects to display"
    items:
      icon:
        type: string
        required: true
        description: "Tabler icon name without 'Icon' prefix"
        example: "School"
      text:
        type: string
        required: true
        description: "Step description text"
        example: "Complete our intensive coding bootcamp and graduate within 180 days"
