name: "Numbered Steps"
version: "1.0"
component: "NumberedSteps"
file: "client/src/components/NumberedSteps.tsx"
description: "Displays a numbered list of steps with icons in a 3-column grid layout, with optional title, description and link. Supports both simple single-text steps and detailed multi-item steps with bullet points."

when_to_use: |
  Use for showing sequential processes, how-to guides, or multi-step workflows.
  Great for refund processes, onboarding steps, career development phases, or any content 
  that benefits from numbered, visual step-by-step presentation.
  
  Simple mode: Use `text` for single-line step descriptions (e.g., refund process).
  Detailed mode: Use `title` + `bullets` for steps with multiple bullet points (e.g., career development).

props:
  title:
    type: string
    required: true
    description: "Main heading for the section (h2)"
    example: "How the Refund Works"
    
  description:
    type: string
    required: false
    description: "Optional paragraph text below the title, centered"
    example: "Our commitment to your success is backed by a simple, transparent refund policy. If you've put in the work and followed our proven methodology, but haven't landed a job within 180 days of graduation, you're eligible for a full tuition refund."
    
  description_link:
    type: object
    required: false
    description: "Optional link displayed below the description"
    example:
      text: "Conditions Apply."
      url: "/terms-and-conditions"
    fields:
      text:
        type: string
        description: "Link text"
        example: "Conditions Apply."
      url:
        type: string
        description: "Link URL"
        example: "/terms-and-conditions"
        
  background:
    type: string
    required: false
    description: "Tailwind background class for the section"
    example: "bg-muted/30"
    default: "bg-muted/30"

  bullet_icon:
    type: string
    required: false
    description: "Default Tabler icon name for all bullets (without 'Icon' prefix)"
    example: "Check"
    default: "Check"

  bullet_icon_color:
    type: string
    required: false
    description: "Tailwind color class for bullet icons"
    example: "text-primary"
    default: "text-primary"

  bullet_char:
    type: string
    required: false
    description: "Text character to use instead of icon for bullets (e.g., '•' for dot)"
    example: "•"
    
  steps:
    type: array
    required: true
    description: "Array of step objects to display"
    example:
      - icon: "School"
        text: "Complete our intensive coding bootcamp and graduate within 180 days of your program start date."
      - icon: "Briefcase"
        text: "Actively apply for jobs using our career services, attend all coaching sessions, and follow our job search methodology."
      - icon: "Cash"
        text: "If you haven't received a qualifying job offer within 180 days of graduation, request your full tuition refund."
    items:
      icon:
        type: string
        required: true
        description: "Tabler icon name without 'Icon' prefix"
        example: "School"
      text:
        type: string
        required: false
        description: "Simple step description text (use for single-line steps)"
        example: "Complete our intensive coding bootcamp and graduate within 180 days"
      title:
        type: string
        required: false
        description: "Step title heading (use with bullets for detailed steps)"
        example: "Profile Optimization"
      bullets:
        type: array
        required: false
        description: "Array of bullet point strings (use with title for detailed steps)"
        example:
          - "Polish LinkedIn, GitHub, and portfolio to attract recruiters"
          - "Build a resume that clears applicant tracking systems"
      bullet_icon:
        type: string
        required: false
        description: "Override default bullet icon for this step"
        example: "CircleCheck"
      bullet_icon_color:
        type: string
        required: false
        description: "Override bullet icon color for this step"
        example: "text-chart-5"
      bullet_char:
        type: string
        required: false
        description: "Override with text character for this step's bullets"
        example: "•"
