name: AI Learning Section
version: "1.0"
component: "AILearningSection"
file: "client/src/components/AILearningSection.tsx"
description: "Showcases AI-powered learning tools with Rigobot, feature cards, and optional video content"
when_to_use: |
  Use to highlight Rigobot AI tutor, mentorship benefits, and community learning.
  Best placed after program overview to emphasize unique learning experience.
  
  Variants:
  - feature-tabs (default): Shows 3 interactive hover cards with expandable content panel
  - highlight: Shows text + video side-by-side layout for simple messaging

variants:
  feature-tabs:
    description: "3 interactive hover cards with expandable content panel showing video/image and bullets"
    best_for: "Program pages, detailed feature showcases"
    
  highlight:
    description: "Simple two-column layout with text content and video side-by-side"
    best_for: "Landing pages, quick value propositions"

base_props:
  variant:
    type: string
    required: false
    default: "feature-tabs"
    enum: ["feature-tabs", "highlight"]
    description: "Layout variant to use"
    
  badge:
    type: string
    required: false
    example: "Why 4Geeks?"
    
  title:
    type: string
    required: true
    example: "Why Learn with 4Geeks?"
    
  description:
    type: string
    required: true
    example: "We've developed tools to keep you motivated, prevent you from getting stuck, and accelerate your learning process."

  video_url:
    type: string
    required: false
    description: "YouTube video URL for embedded player"
    example: "https://www.youtube.com/watch?v=6m1Jyya7eCc"

variant_props:
  feature-tabs:
    features:
      type: array
      required: true
      description: "Feature cards to display (recommended: 3)"
      items:
        icon:
          type: string
          description: "Tabler icon name (e.g., Robot, Headset, Users)"
        title:
          type: string
          required: true
        description:
          type: string
        show_rigobot_logo:
          type: boolean
          required: false
        bullets:
          type: array
          required: false
          items:
            text:
              type: string
            icon:
              type: string
              required: false
        video_url:
          type: string
          required: false
        image_id:
          type: string
          required: false
        cta:
          type: object
          required: false
          fields:
            text:
              type: string
            url:
              type: string
            variant:
              type: string
              enum: ["primary", "secondary", "outline"]
    chat_example:
      type: object
      required: false
      description: "Interactive chat demo showing AI tutor in action (legacy)"
      fields:
        bot_name:
          type: string
        bot_status:
          type: string
        user_message:
          type: string
        bot_response:
          type: string

  highlight:
    bullets:
      type: array
      required: false
      description: "Bullet points for key benefits"
      items:
        text:
          type: string
        icon:
          type: string
          required: false
    video_position:
      type: string
      required: false
      enum: ["left", "right"]
      default: "right"
    cta:
      type: object
      required: false
      fields:
        text:
          type: string
        url:
          type: string
        variant:
          type: string
          enum: ["primary", "secondary", "outline"]
