name: AI Learning Section
version: "1.0"
component: AILearningSection
file: client/src/components/career-programs/AILearningSection.tsx
description: Showcases AI-powered learning tools with an interactive chat example
when_to_use: |
  Use to highlight Rigobot AI tutor and LearnPack software.
  Best placed after program overview to emphasize unique learning experience.
props:
  badge:
    type: string
    required: false
    example: AI-Powered
  title:
    type: string
    required: true
    example: Learn Faster with AI Support
  description:
    type: string
    required: true
    example: Our AI tools provide instant feedback and personalized guidance
  features:
    type: array
    required: true
    items:
      icon:
        type: string
        required: true
      title:
        type: string
        required: true
      description:
        type: string
        required: true
    description: "AI features to highlight (recommended: 2)"
  chat_example:
    type: object
    required: false
    properties:
      bot_name:
        type: string
        required: true
      bot_status:
        type: string
        required: true
      user_message:
        type: string
        required: true
      bot_response:
        type: string
        required: true
    description: Interactive chat demo showing AI tutor in action
  video_url:
    type: string
    required: false
  highlight:
    type: object
    required: false
    properties:
      title:
        type: string
        required: true
      description:
        type: string
        required: true
      bullets:
        type: array
        required: false
        items:
          text:
            type: string
            required: true
      cta:
        type: object
        required: false
        properties:
          text:
            type: string
            required: true
          url:
            type: string
            required: true
          variant:
            type: string
            required: true
            options:
              - primary
              - secondary
              - outline
          icon:
            type: string
            required: false
