name: "Career Support Testimonials"
description: "Full testimonials slide with all 12 default students, countries, and achievements"
yaml: |
  - type: testimonials_slide
    version: "1.0"
    title: "Real Careers Start Here — Just Ask Our Students"
    description: "Our grads are in high demand, with over 84% hired within six months of finishing the program."
    testimonials:
      - name: "Loretta Thompson"
        img: "/attached_assets/ttaLoretta_1764725322100.jpeg"
        status: "Graduated"
        country:
          name: "United States of America"
          iso: "us"
        contributor: "United Way Miami"
        description: "Loretta joined in 2022 and graduated in 2023. She already found a job within the next few months and has fulfilled the whole circle of skills+job that we all want to complete!"
        achievement: "She got a 45% increase in her salary"
      - name: "Rich Akers"
        img: "/attached_assets/Akers_1764725327796.jpeg"
        status: "Graduated"
        country:
          name: "United States of America"
          iso: "us"
        contributor: "Clark University"
        description: "Richard is a great developer that just transitioned from a different background and is now working as a web dev in the tech field."
        achievement: "He got a 30% increase in his salary"
      - name: "MaiLinh Tran"
        img: "/attached_assets/MaiLinh_1764725334980.png"
        status: "Graduated"
        country:
          name: "United States of America"
          iso: "us"
        contributor: "Clark University"
        description: "An entrepreneur with a passion for technology is now focusing on the dev side of their endeavour."
        achievement: "She has launched her startup, is capable of hiring new tech talent and coordinates a dev team!"
      - name: "Jorge Martín Coimbra"
        img: "/attached_assets/coimbra_1764725341501.png"
        status: "Graduated"
        country:
          name: "Uruguay"
          iso: "uy"
        contributor: "UTEC-BID"
        description: "Martín joined the first program that we launched together with UTEC and IDB. He got a better paying job, a career that he is passionate about and a new professional life."
        achievement: "He got a 100% increase in his salary"
      - name: "Jean St. Cloud"
        img: "/attached_assets/JeanSt.Cloud_1764725356935.jpeg"
        status: "Graduated"
        country:
          name: "United States of America"
          iso: "us"
        contributor: "Clark"
        description: "Jean is transitioning from other industries (Music) and is finding his way into Tech. He got it with the support of Clark University and is already performing as a developer and a Mentor."
        achievement: "He got a 100% increase in his salary"
      - name: "Alexandra Espinoza"
        img: "/attached_assets/AlexandraEspinoza_1764725386161.jpeg"
        status: "Graduated"
        country:
          name: "Costa Rica"
          iso: "cr"
        contributor: "CINDE-BID"
        description: "Alexandra came from a total different background is been a huge revelation for her and everyone around her. She is now a successful and talented software developer in Costa Rica."
        achievement: "She got a 100% increase in her salary"
      - name: "Gabriel Salazar"
        img: "/attached_assets/GabrielSalazar_1764725392872.jpeg"
        status: "Graduated"
        country:
          name: "Costa Rica"
          iso: "cr"
        contributor: "CINDE-BID"
        description: "Gabriel was already a support specialist at Microsoft and after completing the program he was able to achieve a new position within Microsoft where he is now working as a Software Engineer."
        achievement: "He got a 50% increase in his salary"
      - name: "Laura Magallanes"
        img: "/attached_assets/Laura_1764725397398.jpeg"
        status: "Graduated"
        country:
          name: "Uruguay"
          iso: "uy"
        contributor: "UTEC-BID"
        description: "Laura is just extraordinary. From a little town in Uruguay with no experience in Coding, she is now a woman head of household, an Instructor and a Program Coordinator."
        achievement: "She got a 120% increase in her salary"
      - name: "Melanie Galaretto"
        img: "/attached_assets/MelamnieGalaretto_1764725408397.jpeg"
        status: "Graduated"
        country:
          name: "Uruguay"
          iso: "uy"
        contributor: "UTEC-BID"
        description: "Melanie is a young professional who is dreaming of achieving a life that now she owns. She is a resourceful and committed software developer working for a software firm in her home country."
        achievement: "She got a +100% increase in her salary"
      - name: "Natia Lombardo"
        img: "/attached_assets/NatiaLombardo_1764725413363.jpeg"
        status: "Graduated"
        country:
          name: "Uruguay"
          iso: "uy"
        contributor: "UTEC-BID"
        description: "Natia is a philosopher and a software developer. Currently working as a QA Engineer of a huge and successful International firm."
      - name: "Luis Larraburo"
        img: "/attached_assets/LuisLarraburo_1764725418057.jpeg"
        status: "Graduated"
        country:
          name: "Costa Rica"
          iso: "cr"
        contributor: "CINDE-BID"
        description: "Luis came to the program without any previous experience, He is now a software developer working on a tech firm in Costa Rica."
        achievement: "He got a 50% increase in his salary"
      - name: "Leandro Matonte"
        img: "/attached_assets/Leandro_1764725403142.jpeg"
        status: "Graduated"
        country:
          name: "Uruguay"
          iso: "uy"
        contributor: "UTEC-BID"
        description: "Leandro got into the program with the expectation to achieve a better understanding and some coding skills that will help with his decision of being a computer scientist graduate. Now he is a software developer at a tech firm in Uruguay."
        achievement: "He got a 60% increase in his salary"
