name: "Credibility Section"
version: "1.0"
component: "CredibilitySection"
file: "client/src/components/career-programs/CredibilitySection.tsx"
description: "Stats cards and featured logos showing social proof"

when_to_use: |
  Use to build trust with impressive numbers and recognizable brands.
  Place near the bottom of the page before final CTA.

props:
  title:
    type: string
    required: true
    example: "Trusted by Thousands"
    
  stats:
    type: array
    required: true
    description: "Key statistics (recommended: 4 stats)"
    items:
      value:
        type: string
        example: "4,000+"
      label:
        type: string
        example: "Graduates"
        
  featured_in:
    type: object
    required: false
    description: "Press/partner logos"
    fields:
      label:
        type: string
        example: "Featured In"
      logos:
        type: array
        example: ["Forbes", "Newsweek", "Course Report", "SwitchUp"]
