name: "Hero Section"
version: "1.0"
component: "Hero"
file: "client/src/components/hero/Hero.tsx"
description: "Main banner at the top of the page with title, subtitle, and call-to-action. Supports multiple layout variants."

when_to_use: |
  Every page should start with a hero section. Choose the variant that best fits your content:
  - singleColumn: Centered content with optional trust bar and award badges (best for program pages)
  - showcase: 3-column layout with images on sides (best for landing pages)
  - twoColumn: Text on left with video on right (best for feature pages)

variants:
  singleColumn:
    description: "Centered single column with badge, title, subtitle, CTAs, trust bar, and award badges"
    best_for: "Program pages, course pages"
  showcase:
    description: "3-column layout with images on left/right, centered content with trust bar"
    best_for: "Landing pages, marketing pages"
  twoColumn:
    description: "Two column layout with text on left and video on right"
    best_for: "Feature pages, product showcases"

props:
  variant:
    type: string
    required: true
    options: ["singleColumn", "showcase", "twoColumn"]
    description: "Layout variant to use"
    example: "singleColumn"

  title:
    type: string
    required: true
    description: "Main headline (keep under 60 characters for best display)"
    example: "Full Stack Development with AI"

  subtitle:
    type: string
    required: false
    description: "Supporting text below title explaining the value proposition"
    example: "Learn at your own pace with AI-powered tools and unlimited mentorship"

variant_props:
  singleColumn:
    badge:
      type: string
      required: false
      description: "Small label displayed above the title"
      example: "Career Program"
    cta_buttons:
      type: array
      required: true
      description: "Call-to-action buttons (recommended: 2 buttons max)"
      items:
        text:
          type: string
          description: "Button label"
        url:
          type: string
          description: "Link destination"
        variant:
          type: string
          options: ["primary", "outline"]
        icon:
          type: string
          required: false
          description: "Tabler icon name (without 'Icon' prefix)"
    trust_bar:
      type: object
      required: false
      description: "Social proof with ratings"
      properties:
        rating:
          type: string
          example: "4.8/5"
        rating_count:
          type: string
          example: "2,500+"
        trusted_text:
          type: string
          example: "Trusted by 10,000+ students"
    award_badges:
      type: array
      required: false
      description: "Award logos to display"
      items:
        name:
          type: string
        source:
          type: string
        year:
          type: string
          required: false

  showcase:
    cta_button:
      type: object
      required: true
      description: "Single call-to-action button"
      properties:
        text:
          type: string
        url:
          type: string
        variant:
          type: string
    trust_bar:
      type: object
      required: false
      description: "Social proof with ratings"
    left_images:
      type: array
      required: false
      description: "Images to display on the left side"
      items:
        src:
          type: string
        alt:
          type: string
    right_images:
      type: array
      required: false
      description: "Images to display on the right side"
    show_arrow:
      type: boolean
      required: false
      description: "Show decorative arrow pointing to CTA"

  twoColumn:
    welcome_text:
      type: string
      required: false
      description: "Text displayed above the title"
      example: "Welcome to"
    brand_mark:
      type: object
      required: false
      description: "Configurable brand text with colored highlight"
      properties:
        prefix:
          type: string
          required: false
          description: "Text before the highlighted portion"
          example: "Geek"
        highlight:
          type: string
          required: true
          description: "The highlighted/colored portion of the brand"
          example: "FORCE"
        suffix:
          type: string
          required: false
          description: "Text after the highlighted portion"
          example: ":"
        color:
          type: string
          required: false
          options: ["primary", "accent", "chart-1", "chart-2", "chart-3", "chart-4", "chart-5"]
          default: "primary"
          description: "Semantic color token for the highlight"
          example: "chart-5"
    description:
      type: string
      required: false
      description: "Longer description text below subtitle"
    video_id:
      type: string
      required: true
      description: "YouTube video ID"
      example: "dQw4w9WgXcQ"
    video_title:
      type: string
      required: false
      description: "Accessible title for the video"
    video_ratio:
      type: string
      required: false
      description: "Video aspect ratio"
      options: ["16:9", "9:12"]
      default: "9:12"
