name: "Default"
description: "Default highlight variant showing key statistics with icons and values"
yaml: |
  - type: features_grid
    version: "1.0"
    variant: highlight
    title: Key Features
    subtitle: Discover what makes us different
    columns: 3
    icon_color: "#0097CD"
    items:
      - icon: Star
        value: "100%"
        title: Satisfaction Rate
      - icon: Users
        value: "10K+"
        title: Active Users
      - icon: Award
        value: "5★"
        title: Average Rating