name: Testimonials Slide
version: "1.0"
component: TestimonialsSlide
file: client/src/components/TestimonialsSlide.tsx
description: >-
  A sliding marquee of testimonial cards with photos, country flags, and achievement badges. Cards auto-scroll
  horizontally and pause on hover.
when_to_use: >-
  Use this component for showcasing multiple student testimonials with rich content including photos, country info, and
  achievements. Best for career support and program pages where social proof is important.
props:
  title:
    type: string
    required: true
    description: Main heading for the testimonials section
    example: Real Careers Start Here — Just Ask Our Students
  description:
    type: string
    required: true
    description: Supporting text that introduces the testimonials
    example: Our grads are in high demand, with over 84% hired within six months of finishing the program.
  background:
    type: string
    required: false
    description: "Background color class (default: bg-sidebar)"
    example: bg-muted
  related_features:
    type: array
    required: false
    items:
      type: string
      enum:
        - online-platform
        - mentors-and-teachers
        - price
        - career-support
        - content-and-syllabus
        - job-guarantee
        - full-stack
        - cybersecurity
        - data-science
        - applied-ai
        - ai-engineering
        - outcomes
        - scholarships
        - rigobot
        - learnpack
        - certification
    description: Select up to 3 topics to pull testimonials from centralized data. Sorted by match count and priority. Priority 1 = highest. Max 9 testimonials displayed.
    example: ["career-support", "job-guarantee"]
  testimonials:
    type: array
    required: false
    deprecated: true
    items:
      name:
        type: string
        required: true
      img:
        type: string
        required: true
      country:
        type: object
        required: true
        properties:
          name:
            type: string
          iso:
            type: string
      contributor:
        type: string
        required: true
      description:
        type: string
        required: true
      status:
        type: string
        required: false
      achievement:
        type: string
        required: false
    description: "Deprecated: Use related_features instead. Inline testimonials as fallback only."
