name: FeaturesGrid
description: A flexible grid of feature cards with icons, titles, descriptions, and optional links. Cards are collapsible on mobile for better UX.
when_to_use: Use when showcasing multiple features, programs, services, or offerings in a grid layout. Ideal for program listings, feature highlights, or service comparisons.

props:
  type:
    type: string
    required: true
    description: Must be "features_grid"
    
  version:
    type: string
    required: false
    description: Component version for registry tracking
    
  title:
    type: string
    required: true
    description: Main heading for the section
    
  subtitle:
    type: string
    required: false
    description: Supporting text below the title
    
  items:
    type: array
    required: true
    description: Array of feature items to display
    items:
      id:
        type: string
        required: false
        description: Unique identifier for the item (used for data-testid)
      icon:
        type: string
        required: true
        description: Tabler icon name (without Icon prefix, e.g., "Code", "Rocket", "Shield")
      category:
        type: string
        required: false
        description: Small category label shown above the title
      title:
        type: string
        required: true
        description: Main title for the feature card
      description:
        type: string
        required: true
        description: Descriptive text for the feature
      link_url:
        type: string
        required: false
        description: URL for the "Read More" or action link
      link_text:
        type: string
        required: false
        description: Text for the link (defaults to "Read More")
        
  columns:
    type: number
    required: false
    default: 3
    description: Number of columns on desktop (1-4)
    
  collapsible_mobile:
    type: boolean
    required: false
    default: true
    description: Whether cards collapse on mobile with a toggle arrow
    
  background:
    type: string
    required: false
    description: Background color class (e.g., "bg-muted/30", "bg-primary/5")
