name: FeaturesGrid
version: "1.0"
component: FeaturesGrid
file: client/src/components/features_grid/FeaturesGrid.tsx
description: >-
  A unified grid component with three variants - "highlight" for stats/metrics cards, "detailed" for full feature cards
  with descriptions and links, and "spotlight" for interactive cards with auto-rotation and hover highlighting.
when_to_use: >
  Use the "highlight" variant (default) when showcasing key metrics, statistics, or simple features with optional
  values.

  Use the "detailed" variant when showcasing programs, services, or features that need full descriptions, categories,
  and action links.

  Use the "spotlight" variant when you want one card to be prominently highlighted while others appear faded,
  with automatic rotation between cards and hover interaction support.
variants:
  detailed: {}
  spotlight: {}
variant_props:
  detailed: {}
  spotlight:
    spotlight_config:
      type: object
      required: false
      description: Configuration for the spotlight behavior
      properties:
        initial_index:
          type: number
          required: false
          description: Which item to highlight initially (0-indexed). Defaults to 0.
        auto_rotate_ms:
          type: number
          required: false
          description: Milliseconds between auto-rotation. Defaults to 4000. Set to 0 to disable.
        pause_on_hover:
          type: boolean
          required: false
          description: Whether to pause auto-rotation when user hovers. Defaults to true.
props:
  title:
    type: string
    required: false
    description: Main heading for the section
  subtitle:
    type: string
    required: false
    description: Supporting text below the title
  items:
    type: array
    required: true
    items:
      id:
        type: string
        required: false
      icon:
        type: string
        required: false
      icon_color:
        type: string
        required: false
      image:
        type: object
        required: false
        properties:
          src:
            type: string
            required: true
          alt:
            type: string
            required: true
      category:
        type: string
        required: false
      title:
        type: string
        required: true
      description:
        type: string
        required: true
      link_url:
        type: string
        required: false
      link_text:
        type: string
        required: false
    description: Array of items to display (structure varies by variant)
  columns:
    type: number
    required: false
    description: Number of columns on desktop (1-4)
  icon_color:
    type: string
    required: false
    description: Hex color for all icons in this grid (e.g., "#0097CD" for blue). If not specified, icons use their default colors.
  collapsible_mobile:
    type: boolean
    required: false
  background:
    type: string
    required: false
    description: Background color class (e.g., "bg-muted/30", "bg-primary/5")
