name: Human and AI Duo
version: "1.0"
component: HumanAndAIDuo
file: client/src/components/HumanAndAIDuo.tsx
description: Displays human mentorship and AI assistant benefits side by side with collapsible bullet groups and optional image
when_to_use: |
  Use for showcasing the combination of human mentors and AI-powered tools
  (like Rigobot). Perfect for support pages, learning pages, or any section
  that highlights both human expertise and AI assistance working together.
props:
  heading:
    type: string
    required: true
    description: Main section heading
    example: "Human + AI: The Perfect Support Duo"
  description:
    type: string
    required: true
    description: Section description text
    example: Learning works best when human expertise and AI support come together.
  bullet_groups:
    type: array
    required: true
    description: Array of groups containing title, optional icon/image, and bullets
    items:
      title:
        type: string
        required: true
        description: Group title (e.g., "Our Team of Expert Mentors:")
      description:
        type: string
        required: false
        description: Optional description for the group
      image:
        type: string
        required: false
        description: Optional image URL for the group icon
      icon:
        type: string
        required: false
        description: Optional Tabler icon name for the group
      bullets:
        type: array
        required: false
        items:
          text:
            type: string
            required: true
          icon:
            type: string
            required: false
  footer_description:
    type: string
    required: false
    description: Optional italic footer text below the bullet groups
    example: Together, human mentorship and AI-powered tools accelerate your learning.
  image:
    type: string
    required: false
    description: Optional side image URL
    example: /attached_assets/support-image.png
  image_alt:
    type: string
    required: false
    description: Alt text for the side image
    example: Woman working on laptop
  background:
    type: string
    required: false
    description: Tailwind background class
    example: bg-primary/5
