name: "Footer CTA Section"
version: "1.0"
component: "FooterCTASection"
file: "client/src/components/career-programs/FooterCTASection.tsx"
description: "Full-width call-to-action section with primary background"

when_to_use: |
  Use as the final push before the footer.
  Should have strong, action-oriented copy.

props:
  title:
    type: string
    required: true
    example: "Ready to Start Your Tech Career?"
    
  subtitle:
    type: string
    required: false
    example: "Join thousands of graduates who have transformed their careers"
    
  buttons:
    type: array
    required: true
    description: "CTA buttons (recommended: 2)"
    items:
      text:
        type: string
      url:
        type: string
      variant:
        type: string
        options: ["secondary", "outline"]
