name: Lead Form
version: "1.0"
component: LeadForm
file: client/src/components/LeadForm.tsx
description: >-
  Lead capture form with configurable fields, auto-detection from session, and consent checkboxes. Submits to marketing
  API.
when_to_use: |
  Use this component when you need to collect user information for lead generation:
  - Program signup pages
  - Landing pages with contact forms
  - Request information sections
  - Newsletter signups with extended data collection
props:
  variant:
    type: string
    required: false
    options:
      - stacked
      - inline
    description: Layout variant to use
    example: stacked
  title:
    type: string
    required: false
    description: Form heading
    example: Start Your Tech Career Today
  subtitle:
    type: string
    required: false
    description: Supporting text below title
    example: Get free information about our programs
  submit_label:
    type: string
    required: false
    description: Text for the submit button
    example: Request Info
  tags:
    type: string
    required: false
    description: Tags to associate with the lead
    example: website-lead,landing-page
  automations:
    type: string
    required: false
    description: Automation level for the lead
    example: strong
  fields:
    type: object
    required: false
    properties:
      email:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
            description: Use 'auto' for auto-detection or a static value
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Email field (always required when visible)
      first_name:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: First name field
      last_name:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Last name field
      phone:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Phone number field
      program:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
            description: Use 'auto' for page context detection or program slug
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Program selection dropdown
      region:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Region dropdown (auto-detected from session)
      location:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Campus location dropdown (auto-detected from session)
      coupon:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Coupon code field (can be pre-filled from URL)
      comment:
        type: object
        required: false
        properties:
          visible:
            type: boolean
            required: false
          required:
            type: boolean
            required: false
          default:
            type: string
            required: false
          helper_text:
            type: string
            required: false
          placeholder:
            type: string
            required: false
        description: Free-form comment textarea
    description: Configuration for each form field. Each field can have visible, required, and default properties.
  success:
    type: object
    required: false
    properties:
      url:
        type: string
        required: false
        description: Redirect URL after success
        example: /thank-you
      message:
        type: string
        required: false
        description: Success message to display (if no url)
        example: Thanks! We'll contact you within 24 hours.
    description: What happens after successful submission
  terms_url:
    type: string
    required: false
    description: URL for Terms and Conditions link
  privacy_url:
    type: string
    required: false
    description: URL for Privacy Policy link
  show_consent:
    type: boolean
    required: false
  show_terms:
    type: boolean
    required: false
  className:
    type: string
    required: false
  turnstile:
    type: object
    required: false
    properties:
      enabled:
        type: boolean
        required: false
        description: Enable Cloudflare Turnstile verification (default true)
      theme:
        type: string
        required: false
        options:
          - light
          - dark
          - auto
        description: Turnstile widget theme
      size:
        type: string
        required: false
        options:
          - normal
          - compact
        description: Turnstile widget size
    description: Cloudflare Turnstile bot protection configuration
