name: Syllabus Section
version: "1.0"
component: SyllabusSection
file: client/src/components/career-programs/SyllabusSection.tsx
description: Expandable curriculum modules showing what students will learn
when_to_use: |
  Use to display the course curriculum in an organized, scannable format.
  Shows module titles with expandable descriptions.
props:
  title:
    type: string
    required: true
    description: Section heading
    example: Get Job-Ready with Our Syllabus!
  subtitle:
    type: string
    required: false
    description: Supporting description
    example: >-
      We've fine-tuned our course content with hundreds of job positions to prepare you for a successful entry into
      tech.
  modules:
    type: array
    required: true
    items:
      title:
        type: string
        required: true
        description: Module name
        example: Introduction To HTML And CSS
      description:
        type: string
        required: true
        description: What students will learn in this module
        example: >-
          Learn to create web structures with HTML and style them with CSS, essential for building visually appealing
          and functional websites.
    description: "List of curriculum modules (recommended: 5-8 modules)"
