name: Graduates Stats
version: "1.0"
component: GraduatesStats
file: client/src/components/GraduatesStats.tsx
description: Display graduate outcomes with image collage and statistics. Supports multiple layout variants.
when_to_use: |
  Use for showcasing graduate outcomes, success metrics, or achievement statistics.
  The collage creates visual interest while stats communicate key results.
  Great for career pages, outcomes sections, or testimonial areas.
variants:
  standard:
    description: Default layout with image collage on left and stacked stats on right
    best_for: General use, career outcomes pages
  fullBleed:
    description: Two featured images bleed to the left screen edge with collage and compact stats
    best_for: Hero-like impact sections, landing pages
props:
  variant:
    type: string
    required: false
    options:
      - standard
      - fullBleed
    description: Layout variant - standard is default, fullBleed adds two full-bleed images on the left
    default: standard
  heading:
    type: string
    required: false
    description: Main heading text displayed above the component
    example: "Does the Job Guarantee deliver results?"
  subheading:
    type: string
    required: false
    description: Descriptive text below the heading
    example: "Yes, and we've got the numbers to back it up."
  stats:
    type: array
    required: true
    description: List of statistics to display
    items:
      value:
        type: string
        required: true
        description: The statistic value (e.g., "84", "3-6")
      unit:
        type: string
        required: false
        description: The unit displayed smaller after the value (e.g., "%", "months")
      label:
        type: string
        required: true
        description: Label explaining the statistic (e.g., "Job placement rate")
  collage_images:
    type: array
    required: true
    description: List of images for the 12-column grid layout
    items:
      image_id:
        type: string
        required: true
        description: ID of the image from the image registry
      col_span:
        type: number
        required: false
        description: Number of columns to span (1-12)
        default: 6
      row_span:
        type: number
        required: false
        description: Number of rows to span
        default: 2
  featured_images:
    type: array
    required: false
    description: Two featured images for the fullBleed variant (displayed on left edge). Required when variant is fullBleed.
    items:
      image_id:
        type: string
        required: true
        description: ID of the featured image from the image registry
  background:
    type: string
    required: false
    description: Background color class (e.g., "bg-primary/5")
    default: ""
