name: Why Learn AI Section
version: "1.0"
component: WhyLearnAISection
file: client/src/components/why-learn-ai/WhyLearnAI.tsx
description: Compelling section about the importance of learning AI-powered development
when_to_use: |
  Use to motivate students about the future of AI in software development.
  Creates urgency and explains why this skill set matters.
variants:
  default:
    description: Original design with man-with-laptop illustration
    best_for: General motivation sections
  laptop-edge:
    description: Modern design with code editor laptop extending to screen edge with decorative background
    best_for: Tech-focused pages, data science programs
props:
  variant:
    type: string
    required: false
    description: Visual style variant
    options:
      - default
      - laptop-edge
    example: default
  title:
    type: string
    required: true
    description: Main headline
    example: Why Should I Learn to Build and Code with AI?
  subtitle:
    type: string
    required: true
    description: Supporting headline
    example: Software Development as You Know It Will Cease to Exist
  description:
    type: string
    required: true
    description: Detailed explanation of why AI coding matters
    example: >-
      Coding with AI will become a new standard, but it's a very different profession from traditional software
      development.
  cta:
    type: object
    required: false
    properties:
      text:
        type: string
        required: true
        example: Join now!
      url:
        type: string
        required: true
        example: /signup
      variant:
        type: string
        required: true
        options:
          - primary
          - secondary
          - outline
      icon:
        type: string
        required: false
    description: Call-to-action button
