name: Who's Hiring Section
version: "1.0"
component: WhosHiring
file: client/src/components/whos-hiring/WhosHiring.tsx
description: Display company logos showing where graduates are hired. Supports grid and carousel variants.
when_to_use: |
  Use this section to build trust by showcasing real employers who have hired your graduates.
  Place after why_learn_ai and before testimonials for maximum social proof impact.
  Include 8-12 logos for optimal display.
variants:
  - name: grid
    description: Paginated grid layout with navigation dots
  - name: carousel
    description: Supabase-style auto-scrolling masonry carousel with grayscale logos
props:
  variant:
    type: string
    required: false
    default: grid
    enum: [grid, carousel]
    description: Display variant - 'grid' for paginated layout, 'carousel' for auto-scrolling masonry
  title:
    type: string
    required: true
    description: Section heading
    example: Who's Hiring Our Graduates?
  subtitle:
    type: string
    required: false
    description: Supporting text below the title
    example: Our alumni work at top companies around the world
  description:
    type: string
    required: false
    description: Longer explanatory text about hiring partners and career outcomes
    example: From startups to Fortune 500 companies, our graduates are making an impact across industries.
  logos:
    type: array
    required: true
    items:
      src:
        type: string
        required: true
        description: URL path to the logo image
        example: /attached_assets/microsoft_1764719829995.png
      alt:
        type: string
        required: true
        description: Company name for accessibility
        example: Microsoft
    description: "List of company logos (recommended: 8-12 for smooth carousel)"
