name: "Features Quad - Default"
description: "Header with images and 4 feature cards in a 2x2 grid layout"
yaml: |
  - type: features_quad
    version: "1.0"
    variant: default
    heading: "Why Choose Our AI Engineering Program?"
    description: "Get the skills, support, and job placement assistance you need to launch your career in AI engineering."
    images:
      - image_id: "student-1"
        alt: "Student 1"
      - image_id: "student-2"
        alt: "Student 2"
      - image_id: "student-3"
        alt: "Student 3"
      - image_id: "student-4"
        alt: "Student 4"
    cards:
      - icon: "Trophy"
        title: "Industry Recognition"
        description: "Ranked among the top coding bootcamps by Forbes, Course Report, and Career Karma."
      - icon: "Wallet"
        title: "Affordable Tuition"
        description: "Among the most affordable tuition of any top-ranked bootcamp, with flexible payment options."
      - icon: "Clock"
        title: "Flexible Schedule"
        description: "Learn at your own pace with part-time and full-time options to fit your lifestyle."
      - icon: "Users"
        title: "Career Support"
        description: "Get unlimited 1:1 mentorship and job placement assistance for life."
    footer_description: "Join thousands of graduates who have launched successful tech careers."
    background: "bg-background"
