name: CTA Banner Section
version: "1.0"
component: CTABannerSection
file: client/src/components/CTABannerSection.tsx
description: Full-width call-to-action section with primary background. Supports single CTA or multiple buttons.
when_to_use: |
  Use as a call-to-action section anywhere on the page.
  Can be placed before footer or between content sections.
  Should have strong, action-oriented copy.
props:
  title:
    type: string
    required: true
    example: Ready to Start Your Tech Career?
  subtitle:
    type: string
    required: false
    example: Join thousands of graduates who have transformed their careers
  cta_text:
    type: string
    required: false
    description: Single CTA button text (use this OR buttons array)
    example: Start Learning Now
  cta_url:
    type: string
    required: false
    description: Single CTA button URL (required if cta_text is provided)
    example: /apply
  buttons:
    type: array
    required: false
    items:
      text:
        type: string
        required: true
      url:
        type: string
        required: true
      variant:
        type: string
        required: true
        options:
          - primary
          - secondary
          - outline
      icon:
        type: string
        required: false
    description: Multiple CTA buttons (use this OR cta_text/cta_url)
  background:
    type: string
    required: false
