name: Awards Marquee Section
version: "1.0"
component: AwardsMarquee
file: client/src/components/AwardsMarquee.tsx
description: Displays a continuously scrolling horizontal band of award logos using react-fast-marquee. Ideal for showcasing multiple awards and certifications.
when_to_use:
  - Display many award logos in a compact scrolling band
  - Create visual movement and engagement on landing pages
  - Show certifications or accreditations from multiple sources
  - Build trust through animated third-party validation
props:
  speed:
    type: number
    required: false
    description: Scroll speed in pixels per second (default 40)
  pauseOnHover:
    type: boolean
    required: false
    description: Whether to pause scrolling on hover (default true)
  gradient:
    type: boolean
    required: false
    description: Whether to show fade gradient at edges (default true)
  gradientWidth:
    type: number
    required: false
    description: Width of fade gradient in pixels (default 100)
  items:
    type: array
    required: true
    items:
      id:
        type: string
        required: true
      alt:
        type: string
        required: true
      logo:
        type: string
        required: false
      logoHeight:
        type: string
        required: false
      source:
        type: string
        required: false
      name:
        type: string
        required: false
      year:
        type: string
        required: false
