name: "Default Stats"
description: "Standard stats section with title and description for career support pages"
yaml: |
  - type: stats_section
    version: "1.0"
    title: "Does the Job Guarantee deliver results you can count on?"
    description: "Yes, and we've got the numbers to back it up. These stats reflect our full graduate community and demonstrate the proven impact of our programs across the board."
