name: "Features Checklist"
version: "1.0"
component: "FeaturesChecklistSection"
file: "client/src/components/career-programs/FeaturesChecklistSection.tsx"
description: "Grid of checkmark items highlighting program benefits"

when_to_use: |
  Use for a quick scannable list of what's included.
  Keep items short and benefit-focused.

props:
  title:
    type: string
    required: true
    example: "What You Get"
    
  items:
    type: array
    required: true
    description: "List of benefit items (recommended: 6-8 items)"
    items:
      text:
        type: string
        example: "Learn at your own pace"
