name: Banner Section
version: "1.0"
component: Banner
file: client/src/components/Banner.tsx
description: A centered banner layout with optional avatars on top border, title, description, and CTA button. Supports different background styles including gradient.