name: "Product Showcase"
description: "Two column layout with welcome text, brand mark, title, description on left and embedded video on right"
yaml: |
  - type: hero
    version: "1.0"
    variant: productShowcase
    welcome_text: "Welcome to"
    brand_mark:
      prefix: "Geek"
      highlight: "FORCE"
      suffix: ":"
      color: "chart-5"
    title: "Career Development"
    subtitle: "for the AI Era"
    description: "Get unlimited 1:1 career support designed for your unique profile and goals—for life. From resume and portfolio building to interviews and AI-driven hiring platforms."
    video_id: "-2ZvlgDnltc"
    video_title: "GeekForce Career Support"
    video_ratio: "9:12"
