name: Product Showcase with Image
description: Two column layout with form, trust bar, and product image on right (no video)
variant: productShowcase
yaml: |-
  - type: hero
    version: "1.0"
    variant: productShowcase
    welcome_text: "Welcome to"
    brand_mark:
      prefix: "Geek"
      highlight: "FORCE"
      suffix: ":"
      color: "chart-5"
    title: "Career Development"
    subtitle: "for the AI Era"
    description: "Get unlimited 1:1 career support designed for your unique profile and goals—for life. From resume and portfolio building to interviews and AI-driven hiring platforms."

    form:
      placeholder: "Enter your work email"
      button_text: "Sign up free →"
      helper_text: "Keep work and life separate by using your work email"
    trust_bar:
      rating: "4.5"
      review_count: "Based on 5149+ reviews"
      review_logos:
        - name: "Google"
          logo: "/attached_assets/google_1765590146414.webp"
        - name: "Course Report"
          logo: "/attached_assets/course-report_1765590146414.webp"
        - name: "SwitchUp"
          logo: "/attached_assets/switchup_1765590146414.webp"
    image:
      src: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800"
      alt: "Product dashboard screenshot"
