name: "Product Showcase with Background"
description: "Two column layout with welcome text, brand mark, title, description on left and embedded video on right. Features a full-width background image."
yaml: |
  - type: hero
    version: "1.0"
    variant: productShowcase
    welcome_text: "Welcome to"
    brand_mark:
      prefix: "Geek"
      highlight: "FORCE"
      suffix: ":"
      color: "chart-5"
    title: "Career Development"
    subtitle: "for the AI Era"
    description: "Get unlimited 1:1 career support designed for your unique profile and goals—for life. From resume and portfolio building to interviews and AI-driven hiring platforms."
    background_image:
      src: "/attached_assets/ai-engineering-light_1765830844948.jpg"
      alt: "AI Engineering Background"
    video_id: "-2ZvlgDnltc"
    video_title: "GeekForce Career Support"
    video_ratio: "9:12"
    form:
      variant: inline
      submit_label: "Get Started →"
      show_consent: false
      show_terms: false
      tags: "website-lead,geekforce"
      fields:
        email:
          visible: true
          placeholder: "Enter your work email"
          helper_text: "Join 10,000+ professionals advancing their careers"
