name: "Product Showcase with Bullets"
description: "Two column layout with welcome text, brand mark, title, description, bullet points, and embedded video. Bullet points highlight key features or benefits below the description."
yaml: |
  - type: hero
    version: "1.0"
    variant: productShowcase
    welcome_text: "Welcome to"
    brand_mark:
      prefix: "Rigo"
      highlight: "bot"
      color: "primary"
    title: "Your AI Coding Mentor"
    subtitle: "24/7 Personalized Support"
    description: "Get unlimited 1:1 coding mentorship and AI-powered guidance from Rigobot 24/7. Never code alone, get instant feedback, and join a global developer community — all designed to help you learn faster, stay motivated, and thrive in tech for life."
    bullets:
      - text: Provides personalized guidance on coding challenges and best practices
      - text: Offers live troubleshooting and debugging support
      - text: Expert bug fixing assistance
      - text: Shares industry insights, career advice, and learning strategies
    video:
      url: "https://www.youtube.com/watch?v=-2ZvlgDnltc"
      ratio: "9:12"
      muted: true
      autoplay: true
      loop: true
    form:
      variant: inline
      submit_label: "Start Learning →"
      show_terms: false
      tags: "website-lead,rigobot"
      fields:
        email:
          visible: true
          placeholder: "Enter your email"
          helper_text: "Join thousands of developers learning with Rigobot"
