name: Award badges Section
version: "1.0"
component: AwardBadges
file: client/src/components/award_badges/AwardBadges.tsx
description: Displays a collection of award badges with logos or text fallback. Supports mobile carousel with autoplay.
when_to_use:
  - Display company awards and recognitions
  - Show certifications or accreditations
  - Highlight industry rankings or badges
  - Build trust through third-party validation
props:
  title:
    type: string
    required: false
  badges:
    type: array
    required: true
    items:
      name:
        type: string
        required: true
      source:
        type: string
        required: true
      year:
        type: string
        required: false
      image:
        type: string
        required: false
