name: Testimonials Section
version: "1.0"
component: TestimonialsSection
file: client/src/components/career-programs/TestimonialsSection.tsx
description: Display student reviews and success stories with ratings, photos, and outcomes
when_to_use: |
  Use testimonials to build trust and show real results from past students.
  Place after the certificate section and before FAQ for maximum impact.
  Include 3-6 testimonials for optimal display across all screen sizes.
props:
  title:
    type: string
    required: true
    description: Section heading
    example: What Our Students Say
  subtitle:
    type: string
    required: false
    description: Supporting text below the title
    example: Real stories from graduates who transformed their careers
  rating_summary:
    type: object
    required: false
    properties:
      average:
        type: string
        required: true
        description: Average rating score
        example: "4.9"
      count:
        type: string
        required: true
        description: Total number of reviews
        example: 2,847
    description: Overall rating display shown above testimonials
  related_features:
    type: array
    required: false
    items:
      type: string
      enum:
        - online-platform
        - mentors-and-teachers
        - price
        - career-support
        - content-and-syllabus
        - job-guarantee
        - full-stack
        - cybersecurity
        - data-science
        - applied-ai
        - ai-engineering
        - outcomes
        - scholarships
        - rigobot
        - learnpack
        - certification
    description: Select up to 3 topics to pull testimonials from centralized data. Sorted by match count and priority. Priority 1 = highest. Max 30 testimonials displayed.
    example: ["career-support", "job-guarantee"]
  items:
    type: array
    required: false
    deprecated: true
    items:
      name:
        type: string
        required: true
        description: Student's full name
        example: Maria Rodriguez
      role:
        type: string
        required: true
        description: Current job title
        example: Software Engineer
      company:
        type: string
        required: false
        description: Current employer
        example: Google
      rating:
        type: number
        required: true
        description: Star rating from 1-5
        example: 5
      comment:
        type: string
        required: true
        description: The testimonial text (keep under 200 characters for best display)
        example: This program changed my life. I went from zero coding experience to landing my dream job in 6 months.
      outcome:
        type: string
        required: false
        description: Badge showing key achievement
        example: Hired in 4 months
      avatar:
        type: string
        required: false
        description: URL to profile photo (uses colorful illustration if not provided)
    description: "Deprecated: Use related_features instead. Inline testimonials as fallback only."
  filter_by_location:
    type: string
    required: false
