name: "Rigobot AI Benefits"
description: "Supabase-style bento grid with 4 cards: 2 on top, 1 wide at bottom left, 1 tall on the right"
yaml: |
  - type: bento_cards
    version: "1.0"
    title: "How Rigobot Keeps You Moving"
    description: "Rigobot is your AI-powered coding companion that ensures you never lose momentum. Whether you're debugging at 2am or preparing for an exam, Rigobot is there to help you push through challenges and keep learning."
    items:
      - icon: CodeReview
        title: "Instant Code Review"
        description: "Get immediate feedback on your code quality, best practices, and potential improvements before you submit."
      - icon: Bug
        title: "Debugging Assistant"
        description: "Step-by-step help to understand and fix errors. Never spend hours stuck on the same problem again."
      - icon: Clock
        title: "Available 24/7"
        description: "Get help whenever you need it, day or night. No waiting for office hours or mentor availability. Rigobot is always ready to assist you with any coding challenge."
      - icon: School
        title: "Homework & Exam Preparation"
        description: "Practice problems, explanations, and study guides to help you ace your assessments. Rigobot adapts to your learning style and pace."
    background: bg-background
