name: "Why Learn AI - Default Variant"
description: "Motivational section with man-with-laptop illustration"
yaml: |
  - type: why_learn_ai
    version: "1.0"
    variant: default
    title: "Why Should I Learn to Build and Code with AI?"
    subtitle: "Software Development as You Know It Will Cease to Exist"
    description: "Coding with AI will become a new standard, but it's a very different profession from traditional software development. The developers who embrace AI tools now will have a significant advantage in the job market."
    cta:
      text: "Join now!"
      url: "/signup"
      variant: "primary"
