name: FAQ Section
version: "1.0"
component: FAQSection
file: client/src/components/FAQSection.tsx
description: Collapsible accordion with frequently asked questions
when_to_use: |
  Use to address common objections and questions.
  Helps with SEO and reduces support inquiries.
props:
  title:
    type: string
    required: true
    example: Frequently Asked Questions
  related_features:
    type: array
    required: false
    items:
      type: string
      enum:
        - online-platform
        - mentors-and-teachers
        - price
        - career-support
        - content-and-syllabus
        - job-guarantee
        - full-stack
        - cybersecurity
        - data-science
        - applied-ai
        - ai-engineering
        - outcomes
        - scholarships
        - rigobot
        - learnpack
        - certification
    description: Select up to 3 topics to pull FAQs from centralized data. Sorted by match count and priority. Max 9 FAQs displayed.
    example: ["career-support", "job-guarantee"]
  items:
    type: array
    required: false
    deprecated: true
    items:
      question:
        type: string
        required: true
        example: Do I need prior coding experience?
      answer:
        type: string
        required: true
        example: No prior experience is required. We start from the fundamentals.
    description: "Deprecated: Use related_features instead. Inline Q&A pairs as fallback only."
  cta:
    type: object
    required: false
    properties:
      text:
        type: string
        required: true
      button_text:
        type: string
        required: true
      button_url:
        type: string
        required: true
